---
namespace: fmjstudios
name: hardening
version: 0.0.1
readme: README.md
authors:
  - Maximilian Gindorfer <info@fmj.dev>
description: Ansible Collection for Initial Server Setup
license_file: "LICENSE"
tags:
  - ubuntu
  - server
  - configuration
  - hardening
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: https://fmj.dev
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore
  - LICENSE
  - Makefile
  - AUTHORS
  - .vscode
  - .github