---
- name: Create Linux Malware Detect's download directory
  ansible.builtin.file:
    path: "{{ download_dir }}"
    state: directory
    recurse: yes
  tags: bootstrap

- name: Maldet | download the Linux Malware Detect tar.gz file from rfxn.com
  ansible.builtin.get_url:
    url: http://www.rfxn.com/downloads/maldetect-current.tar.gz
    dest: "{{ download_dir }}/maldetect-current.tar.gz"
    mode: "0755"
  tags:
    - maldet
    - scanners

- name: Maldet | Unarchive copied package
  ansible.builtin.unarchive:
    src: "{{ download_dir }}/maldetect-current.tar.gz"
    dest: "{{ download_dir }}"
    extra_opts: [--strip-components=1, --no-same-owner]
    copy: no
  tags:
    - maldet
    - scanners

- name: Maldet | Install Linux Malware Detect
  ansible.builtin.command: "{{ download_dir }}/install.sh"
  args:
    chdir: "{{ download_dir }}"
  changed_when: false
  tags:
    - maldet
    - scanners

- name: Maldet | Add maldet to crontab at a random hour
  ansible.builtin.cron:
    name: Run Linux Malware Detect
    hour: "{{ cron_job_hour }}"
    minute: "{{ cron_job_minute }}"
    job: "maldet -u && maldet -a"
    state: present
  changed_when: false
  tags:
    - maldet
    - cron
    - scanners
